add getting socket id
HomeXLabs/pusher-websocket-flutter pull request #19
Opened 2020-04-18 09:01 UTC by MohammedYAmmar

getting the socket id to use to stop the client that broadcasts an event from receiving it

2020-04-18 19:04 UTC, MisterJimson requested changes
Not a bad start. Some feedback noted. Thanks for the help.

2020-04-18 19:04 UTC, MisterJimson commented on android/src/main/java/com/pusherwebsocket/pusher/PusherPlugin.java
> +    }
This looks like iOS Swift code that was just copy pasted into the Android implementation. This would need to be properly implemented in Java to work. Please test on Android if possible before submitting.

2020-04-18 19:04 UTC, MisterJimson commented on lib/pusher.dart
> +  }
I think I would expect this to be an async function that makes the method call and returns the id back directly. _handleEvent is more reacting to events from the pusher SDK.

2020-04-19 06:31 UTC, MohammedYAmmar commented
sorry i have made i mistake when copying the code to the repository
I will change the request with the right code 
I do it like this my app and it is just work fine
when the connection change I call the get socket id from the native code and store it in the var _socketId
coz the socket id will change only when the connection changed.

2020-04-21 12:02 UTC, MisterJimson approved these changes
Thanks for the help!

2020-04-21 12:02 UTC, merged